### ISSUE TITLE
Could you add support to grab the "All Reviews" or "Recent Reviews" rating

### ISSUE THREAD

**Issue by djvj1** [boralyl/steam-wishlist#9]
Title says it all. I'd like to impose the rating of the games on the wishlist card.

**Comment by boralyl** [comment]
Looks like the api does return this data, will just need to do a little investigation to figure out the mapping as they are returned as numbers (8) instead of labels like (Extremely Positive).

**Comment by boralyl** [comment]
@djvj1 Three new attributes were added in the latest release: https://github.com/boralyl/steam-wishlist/releases/tag/v2.1.0

**Comment by djvj1** [comment]
Thanks so much for the quick update!! Once HACS shows the update, I'll test it out.

**Comment by djvj1** [comment]
Would you be able to put an example on how to add this to your wishlist card? Still new to HA and not sure how to add attributes in YAML:
```
type: custom:nintendo-wishlist-card
entity: sensor.steam_wishlist_#####
title: Steam Wishlist
secondary_info:
  attribute: review_desc
entities:
  - attribute: review_desc
    name: Review
image_style: backgroundart
max: 10

```
Above doesn't work, just showing what I tried.
